apiVersion: v1
generated: 2017-03-10T12:31:04.5110303+05:30
repositories:
- caFile: ""
  cache: .helm\repository\cache\stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- caFile: ""
  cache: .helm\repository\cache\local-index.yaml
  certFile: ""
  keyFile: ""
  name: local
  url: http://127.0.0.1:8879/charts
