apiVersion: v1
description: A Helm chart for Dealer Service
name: dealerservice
version: 0.1.0
sources:
- https://dxdevop.visualstudio.com/mrpmicro/_git/code
maintainers:
- name: Parts Unlimited MRP GitHub Team
engine: gotpl
