apiVersion: v1
description: A Helm chart for Order Service
name: orderservice
version: 0.1.1
sources:
- https://dxdevop.visualstudio.com/mrpmicro/_git/code
maintainers:
- name: Parts Unlimited MRP GitHub Team
engine: gotpl
