# Default values for PartsUnlimitedMrp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
apiversion:
  deployment: apps/v1beta1 # for versions 1.8+ use apps/v1beta2
image:
  repository: mypumrpmicro.azurecr.io/pumrp
  name: pumrp-web
  tag: latest
  pullPolicy: Always
labels:
  tier: frontend
  link: PartsUnlimitedMrp
service:
  name: pu-mrp-frontend
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
  imagePullSecrets: puregistrykey
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

